# Generated by Django 4.2.8 on 2023-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faceDetect", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacedetectCriminal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "aadhar_no",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "picture",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "faceDetect_criminal",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FacedetectCriminallastspotted",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "aadhar_no",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "picture",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "faceDetect_criminallastspotted",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FacedetectFile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=100
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=20
                    ),
                ),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "faceDetect_file",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="imageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Criminal",
        ),
        migrations.DeleteModel(
            name="CriminalLastSpotted",
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
