# Generated by Django 4.2.8 on 2023-12-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceDetect', '0002_facedetectcriminal_facedetectcriminallastspotted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagetable',
            fields=[
                ('imageid', models.AutoField(db_column='ImageID', primary_key=True, serialize=False)),
                ('imagedata', models.BinaryField(blank=True, db_column='ImageData', max_length='max', null=True)),
            ],
            options={
                'db_table': 'ImageTable',
                'managed': False,
            },
        ),
    ]
