# Generated by Django 4.2.8 on 2023-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacedetectUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "first_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "faceDetect_user",
                "managed": False,
            },
        ),
    ]
